"""Build a self-contained AgentMesh CLI from a trusted source checkout.

This produces a local binary, not a signed OTA release or an installer.
"""
import argparse
import os
from pathlib import Path
import subprocess
import sys


HIDDEN_MODULES = (
    'brand', 'recall_memory', 'ingest_sessions', 'workflow', 'summarize_memory',
    'sqlite_memory', 'memory_sync', 'sync_worker', 'bounded_digest', 'install_inspect', 'install_setup', 'security_wizard',
    'install_adopt', 'worker_lifecycle', 'worker_diagnostics', 'worker_error_details', 'mac_replace', 'windows_install', 'windows_task', 'console_prompt', 'terminal_progress',
    'omp_memory.parser', 'omp_memory.codex_parser', 'omp_memory.claude_parser',
    'cryptography.hazmat.primitives.asymmetric.ed25519',
)


def build_command(source, dist, work):
    source = Path(source).resolve(strict=True)
    if not (source / 'agentmesh.py').is_file() or not (source / 'schema.sql').is_file() or not (source / 'src' / 'omp_memory').is_dir():
        raise ValueError('source must contain the AgentMesh CLI, schema and parsers')
    dist, work = Path(dist).resolve(), Path(work).resolve()
    if any(path == source or path.is_relative_to(source) for path in (dist, work)):
        raise ValueError('build output must be outside source')
    return [sys.executable, '-m', 'PyInstaller', '--noconfirm', '--clean', '--onefile',
            '--name', 'agentmesh', '--distpath', str(dist), '--workpath', str(work),
            '--specpath', str(work), '--additional-hooks-dir', str(source / 'packaging-hooks'),
            '--paths', str(source), '--paths', str(source / 'src'),
            '--add-data', str(source / 'schema.sql') + os.pathsep + '.',
            *[part for module in HIDDEN_MODULES for part in ('--hidden-import', module)],
            str(source / 'agentmesh.py')]


WINDOWS_SPEC = """# Generated by standalone_build.py; Windows onedir build of both entry points.
cli = Analysis([{cli!r}], pathex={paths!r}, datas=[({schema!r}, '.')],
               hiddenimports={hidden!r}, hookspath=[{hooks!r}])
launcher = Analysis([{launcher!r}], pathex=[{source!r}])
cli_exe = EXE(PYZ(cli.pure), cli.scripts, [], exclude_binaries=True, name='agentmesh', console=True)
launcher_exe = EXE(PYZ(launcher.pure), launcher.scripts, [], exclude_binaries=True, name='agentmeshw', console=False)
COLLECT(cli_exe, cli.binaries, cli.datas, launcher_exe, launcher.binaries, launcher.datas, name='agentmesh')
"""


def windows_build(source, dist, work):
    """One onedir folder: agentmesh.exe, windowless agentmeshw.exe and a shared _internal.

    Nothing is extracted at start, so each process in the logon chain starts
    without unpacking a onefile archive (which antivirus rescans every time).
    """
    source = Path(source).resolve(strict=True)
    build_command(source, dist, work)  # Same source and output-location checks.
    dist, work = Path(dist).resolve(), Path(work).resolve()
    work.mkdir(parents=True, exist_ok=True)
    spec = work / 'agentmesh-windows.spec'
    spec.write_text(WINDOWS_SPEC.format(
        cli=str(source / 'agentmesh.py'), paths=[str(source), str(source / 'src')],
        schema=str(source / 'schema.sql'), hidden=list(HIDDEN_MODULES), hooks=str(source / 'packaging-hooks'),
        launcher=str(source / 'agentmesh_launcher.py'), source=str(source)), encoding='utf-8')
    return spec, [sys.executable, '-m', 'PyInstaller', '--noconfirm', '--clean',
                  '--distpath', str(work / 'collect'), '--workpath', str(work / 'pyinstaller'), str(spec)]


def flatten(collected, dist):
    """Move the COLLECT folder's entries into dist so paths stay dist/agentmesh.exe."""
    dist = Path(dist)
    dist.mkdir(parents=True, exist_ok=True)
    for entry in Path(collected).iterdir():
        target = dist / entry.name
        if target.exists():
            raise ValueError('build output already contains ' + entry.name)
        entry.rename(target)
    Path(collected).rmdir()


def operator_launcher(dist):
    """Adjacent relocatable operator entry, never a production-config default."""
    path = Path(dist) / 'Replace-AgentMesh.command'
    path.write_text('''#!/bin/zsh
set -eu
here="${0:A:h}"
print 'AgentMesh local development trial | not signed/notarized for distribution'
print 'A private replacement manifest is required. Planning precedes REPLACE.'
if (( $# )); then
  manifest="$1"
else
  read 'manifest?Absolute path to private replacement manifest: '
fi
"$here/agentmesh" mac-replace --manifest "$manifest" --binary "$here/agentmesh"
print 'Press Return to close.'
read ignored
''', encoding='utf-8')
    path.chmod(0o700)
    return path


def windows_launcher(dist):
    """Package the reviewed click helpers with native CMD line endings."""
    for name in ('Install-AgentMesh.cmd', 'Upgrade-AgentMesh.cmd', 'Enable-AgentMesh-Autostart.cmd'):
        source = Path(__file__).with_name(name)
        target = Path(dist) / name
        target.write_bytes(source.read_text(encoding='utf-8').replace('\n', '\r\n').encode('utf-8'))
    return Path(dist) / 'Install-AgentMesh.cmd'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dist', type=Path, required=True, help='output directory outside the source tree')
    parser.add_argument('--work', type=Path, required=True, help='private build directory outside the source tree')
    args = parser.parse_args(argv)
    source = Path(__file__).resolve().parent
    if os.name == 'nt':
        _, command = windows_build(source, args.dist, args.work)
        subprocess.run(command, check=True)
        flatten(args.work.resolve() / 'collect' / 'agentmesh', args.dist)
        windows_launcher(args.dist)
    else:
        subprocess.run(build_command(source, args.dist, args.work), check=True)
        if sys.platform == 'darwin':
            operator_launcher(args.dist)
    print(args.dist.resolve() / ('agentmesh.exe' if os.name == 'nt' else 'agentmesh'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
