"""Stable, secret-free worker error codes and operator guidance."""
DETAILS = {
    'worker recorded a cycle failure': ('WORKER_CYCLE_FAILED', 'Inspect the existing instance and local cycle status; do not start a duplicate.'),
    'stale worker metadata; no process was signalled': ('WORKER_STALE', 'The recorded process is absent. Run diagnose and verify other workers before an explicit restart. Do not kill the old PID or delete data.'),
    'worker ownership changed while stopping': ('WORKER_OWNERSHIP_CHANGED', 'Another instance replaced the record. Inspect current state; do not stop a metadata-selected PID.'),
    'worker did not acknowledge stop; no process was signalled': ('WORKER_STOP_TIMEOUT', 'Stop is not confirmed. Inspect the same instance; do not start a duplicate or force-kill from metadata.'),
    'worker already running; stop it first': ('WORKER_ALREADY_RUNNING', 'Inspect the existing instance; do not start another worker.'),
    'worker startup did not finish; nonce stop requested': ('WORKER_START_TIMEOUT', 'A cooperative stop was requested, not confirmed. Inspect state before another start.'),
    'worker failed before a healthy cycle': ('WORKER_START_FAILED', 'Run diagnose and inspect recorded last_error; do not repeatedly start.'),
    'Windows private ACL must be protected': ('PRIVATE_ACL_UNPROTECTED', 'Review the diagnostic target. Use only an approved owner-preserving ACL repair; do not bypass checks or repair recursively.'),
    'Windows private owner/type mismatch': ('PRIVATE_OWNER_MISMATCH', 'Check the invoking user and selected target. Do not take ownership or elevate to bypass the guard.'),
    'private signing file permissions required': ('PRIVATE_PERMISSIONS_REQUIRED', 'Review the diagnostic target and ownership. Do not apply a blanket permissions repair.'),
    'private directory ownership/permissions required': ('PRIVATE_DIRECTORY_PERMISSIONS', 'Review directory ownership and permissions; do not bypass the guard.'),
    'corrupt or foreign worker metadata; manual review required': ('WORKER_METADATA_INVALID', 'Review runtime and instance ownership; do not delete the record or kill its PID automatically.'),
    'corrupt worker nonce': ('WORKER_NONCE_INVALID', 'Review instance ownership; no PID-based stop is authorized.'),
    'database must remain outside exchange': ('DATABASE_IN_EXCHANGE', 'Review existing path binding. Never sync a live SQLite DB or reinitialize it.'),
    'local state must remain separate from exchange': ('LOCAL_STATE_IN_EXCHANGE', 'Review storage layout; do not move or recreate data automatically.'),
    'invalid runtime': ('RUNTIME_INVALID', 'Review the existing runtime format and required fields. Do not replace existing state with setup-new.'),
    'database scope mismatch': ('DATABASE_SCOPE_MISMATCH', 'Review node/group bindings; do not regenerate an identity or rewrite scope.'),
    'database policy changed; explicit review required': ('DATABASE_POLICY_CHANGED', 'Review the signing policy; do not automatically change it.'),
    'strict identity binding mismatch': ('IDENTITY_BINDING_MISMATCH', 'Recover the existing identity; do not generate a replacement key.'),
    'persistent signing key changed': ('IDENTITY_KEY_CHANGED', 'Review identity recovery; do not approve or rotate a key automatically.'),
    'runtime configuration changed; restart after review': ('RUNTIME_CHANGED', 'Review changed configuration and the existing worker before an explicit restart.'),
    'partial first-run installation requires manual review': ('INSTALL_PARTIAL', 'Retain partial files for review; do not delete uncertain contents or bypass the marker.'),
    'package manifest does not match executable': ('PACKAGE_BINARY_MISMATCH', 'Extract the verified bundle into a new folder; do not overwrite a running binary.'),
    'invalid package metadata': ('PACKAGE_METADATA_INVALID', 'Use the original verified BUILD.json; this is not a publisher-signature check.'),
    'no such table: _sync_config': ('DATABASE_SCHEMA_MISSING', 'Review the selected existing database; do not initialize it over existing data.'),
    'database disk image is malformed': ('DATABASE_MALFORMED', 'Preserve the database and use the recovery procedure; do not overwrite it.'),
    'database is locked': ('DATABASE_BUSY', 'Inspect active writers and retry only after review; do not delete WAL/SHM files or force-kill.'),
}
SYSTEM_ERRORS = {
    'FileNotFoundError': ('LOCAL_FILE_MISSING', 'Check the diagnostic target and existing installation; do not initialize replacement data or keys.'),
    'PermissionError': ('LOCAL_ACCESS_DENIED', 'Check the invoking user and target permissions; do not disable security checks.'),
    'JSONDecodeError': ('INVALID_JSON', 'Review the selected JSON file without sharing its contents or credentials.'),
}
